### ISSUE TITLE
Field "id" in SQL Databases

### ISSUE THREAD

**Issue by alaneduaardo** [biggora/caminte#34]
Hi, my name is Alan and I've a problem using SQL databases. Caminte force that my tables have an "id" field and I do not use the default name. How can I fix this?

Best Regards

**Comment by damianof** [comment]
I am facing the same dilemma. Also, how can I import pre-existing data including ids and establish correct relationships?

**Comment by biggora** [comment]
Hi
Use `primaryKeys` parameter, for define any key name as primary.
example here:
https://github.com/biggora/caminte/wiki/Defining-a-Model#define-primary-keys

**Comment by damianof** [comment]
Thank you Alexey. I appreciated your time.
Damiano

**Comment by guilhermeKodama** [comment]
I defined the primary key and still dont work in postgresql.

**Comment by shamrath** [comment]
Hi Alexey Gordeyev, 

Above document is outdated with the latest code, When I use a different field as a primary key instead of 'id' it doesn't work, this creates invalid 'create table SQL query'. To make it works I had to put 'allowNull: false' as a property to avoid my primary key getting NULL property when creating table. 

eg:  
module.exports = function (schema) {
  var Customer = schema.define('customer', {
    customer_id: {type: schema.Integer, allowNull: false},
    // more code here
  }, {
    primaryKeys: ["customer_id"]
  });
  return Customer;
};

Best,
Shameera.
